name: spdx_parser
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  xml: ^5.0.1
  http: ^0.13.0

dev_dependencies:
  pedantic: ^1.8.0
